services:
  whatsapp_go:
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: '10'
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: on-failure
    ports:
      - '3012:3000'
    env_file:
      - src/.env
    volumes:
      - './storages:/app/storages'
      - './statics:/app/statics'
    networks:                     
      - danymed_shared_prod           

networks:                         
  danymed_shared:                 
    external: true                
    name: red_global_danymed_prod
